/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import dao.daoVehiculos;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import dao.Conexion;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author usuario
 */
public class Jfrm_Listar extends javax.swing.JFrame {

    /**
     * Creates new form Jfrm_Listar
     */
    ListasEnlazadas<VehiculosLE> lst = new ListasEnlazadas<>();
    DefaultTableModel listado;

    public Jfrm_Listar() {

        String cls[] = {"Placa", "Fecha", "Hora", "Tipo"};
        listado = new DefaultTableModel(cls, 0);
        initComponents();
        setLocationRelativeTo(null);

        jTable1.getTableHeader().setReorderingAllowed(false); //para q las 3 columnas no se muevan de lugar
        jTable1.getTableHeader().setResizingAllowed(false);  //para q las 3 columnas no se puedan alargar o encoger

        
        
        
        new daoVehiculos().Listar(listado);
            jTable1.updateUI();
        if (listado.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Tabla vacia \n Ingrese un vehiculo");
            btnPDF.setEnabled(false);
            cmbGenerar.setEnabled(false);
        } 

        //Jfrm_Principal.arduino_esta_conectado = "true";
    }

    public void GenerarPDF() {
        Document documento = new Document();
        try {
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/Reporte_vehiculos.pdf"));
            documento.open();
            documento.add(new Paragraph("PARKING MR.GOKU "));
            documento.add(new Paragraph("                                                 Reporte de Base de datos"));
            documento.add(new Paragraph("Fecha: " + new daoVehiculos().getFecha()));
            documento.add(new Paragraph("Hora: " + new daoVehiculos().getHora()));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph(" "));
            PdfPTable tabla = new PdfPTable(4);
            tabla.addCell("Placa");
            tabla.addCell("Fecha");
            tabla.addCell("Hora");
            tabla.addCell("Tipo");
            try {
                Connection conex = DriverManager.getConnection("jdbc:mysql://localhost/bd_vehiculos", "root", "");
                PreparedStatement ps = conex.prepareStatement("SELECT * FROM tbl_vehiculo");
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    do {
                        tabla.addCell(rs.getString(1));
                        tabla.addCell(rs.getString(2));
                        tabla.addCell(rs.getString(3));
                        tabla.addCell(rs.getString(4));

                    } while (rs.next());
                    documento.add(tabla);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERROR EN LA BASE");
            }
            documento.close();
            JOptionPane.showMessageDialog(null, "Archivo PDF creado en ESCRITORIO");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_regresar = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        cmbGenerar = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTable1.setModel(listado);
        jScrollPane1.setViewportView(jTable1);

        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salir.png"))); // NOI18N
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        btnPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pdf.png"))); // NOI18N
        btnPDF.setText("BASE DE DATOS");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        cmbGenerar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un vehiculo", "Auto", "Motocicleta" }));
        cmbGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGenerarActionPerformed(evt);
            }
        });

        jLabel1.setText("Genere un reporte:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbGenerar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_regresar))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPDF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_regresar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(20, 20, 20))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
        Jfrm_Principal abrir = new Jfrm_Principal();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        // TODO add your handling code here:
        GenerarPDF();
    }//GEN-LAST:event_btnPDFActionPerformed

    private void cmbGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGenerarActionPerformed
        if (cmbGenerar.getSelectedIndex() == 1) {
            Generar_PDF_Tipos("Auto", "Auto");
            cmbGenerar.setSelectedIndex(0);

        } else if (cmbGenerar.getSelectedIndex() == 2) {
            Generar_PDF_Tipos("Motocicleta", "Motocicleta");
            cmbGenerar.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cmbGenerarActionPerformed

    public void Generar_PDF_Tipos(String tipo_vehiculo, String con) {

        Document documento = new Document();
        try {
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/Reporte_Tipo_Vehiculo_" + con + ".pdf"));
            documento.open();
            documento.add(new Paragraph("PARKING MR.GOKU "));
            documento.add(new Paragraph("                                                 Reporte de Base de datos"));
            documento.add(new Paragraph("Fecha: " + new daoVehiculos().getFecha()));
            documento.add(new Paragraph("Hora: " + new daoVehiculos().getHora()));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph(" "));
            PdfPTable tabla = new PdfPTable(4);
            tabla.addCell("Placa");
            tabla.addCell("Fecha");
            tabla.addCell("Hora");
            tabla.addCell("Tipo");
            try {
                Connection conex = DriverManager.getConnection("jdbc:mysql://localhost/bd_vehiculos", "root", "");
                PreparedStatement ps = conex.prepareStatement("SELECT * FROM tbl_vehiculo WHERE vh_tipo LIKE '%" + tipo_vehiculo + "%' ");
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    do {
                        tabla.addCell(rs.getString(1));
                        tabla.addCell(rs.getString(2));
                        tabla.addCell(rs.getString(3));
                        tabla.addCell(rs.getString(4));

                    } while (rs.next());
                    documento.add(tabla);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERROR EN LA BASE");
            }
            documento.close();
            JOptionPane.showMessageDialog(null, "Archivo PDF creado en ESCRITORIO");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JComboBox<String> cmbGenerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
